import type { Metadata } from "next";
import "./globals.css";
import MainNavBar from "@/components/main-nav/MainNavBar";
import Footer from "@/components/Footer";
import SessionWrapper from "@/components/SessionWrapper";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <SessionWrapper>
      <html lang="en">
        <body className="flex flex-col items-center font-lora ">
          <div className="2xl:w-[1600px] lg:w-[1360px]">
            <MainNavBar />
            {/* <SidebarTrigger /> */}
            {children}
          </div>
          <Footer />
        </body>
      </html>
    </SessionWrapper>
  );
}
