import type { Metadata } from "next";
import "./globals.css";
import MainNavBar from "@/src/components/main-nav/MainNavBar";
import Footer from "@/src/components/Footer";
import SessionWrapper from "@/src/components/SessionWrapper";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { notFound } from "next/navigation";
import { routing } from "../../i18n/routing";
import { ErrorProvider } from "@/src/context/ErrorContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  if (!routing.locales.includes(locale as any)) {
    notFound();
  }
  const messages = await getMessages();
  return (
    <SessionWrapper>
      <ErrorProvider>
        <html lang={locale}>
          <body className="flex flex-col items-center font-lora ">
            <NextIntlClientProvider messages={messages}>
              <div className="2xl:w-[1600px] lg:w-[1360px]">
                <MainNavBar />
                {/* <SidebarTrigger /> */}
                {children}
              </div>
              <Footer />
              <div id="modal"></div>
            </NextIntlClientProvider>
          </body>
        </html>
      </ErrorProvider>
    </SessionWrapper>
  );
}
